#!/usr/local/bin/gmake -f

.ONESHELL:

godown:
	godown
	
diff:
	diff main.go main.go.expected || true
	diff makedown.go makedown.go.expected || true
	
generate:
	./makedown --out Makefile
	
build:
	go build
	
build-and-notarize:
	goreleaser build --snapshot --rm-dist
	
check-notarized:
	@echo Check the binary is signed
	codesign --display -vvv dist/macos_darwin_amd64_v1/makedown
	
	@echo
	@echo Check the binary is notarized
	spctl --assess --type install -vvv dist/macos_darwin_amd64_v1/makedown
	
build-and-release-snapshot:
	goreleaser release --snapshot --rm-dist
	
build-and-release:
	goreleaser release --rm-dist
	
case1:
	cd tests/case1
	if [ -e Makefile ]; then
	  rm Makefile
	fi
	../../makedown --out Makefile
	diff Makefile Makefile.expected > Makefile.diff
	cat Makefile.diff
	
case2:
	cd tests/case2
	if [ -e Makefile ]; then
	  rm Makefile
	fi
	../../makedown -f EXAMPLE.md
	diff Makefile Makefile.expected > Makefile.diff
	cat Makefile.diff
	
sayhello:
	@echo "Hello, $(WHO)!"
	
saygoodbye:
	@echo "Bye for now," `date +%Y/%m/%d`
	
WHO = makedown

install:
	go install github.com/hirokistring/makedown
	

# This makefile is generated by makedown from "Makefile.md"
